# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hgwr_bfml <- function(g, x, z, y, u, group, bw, kernel, alpha, eps_iter, eps_gradient, max_iters, max_retries, ml_type, verbose) {
    .Call(`_hgwrr_hgwr_bfml`, g, x, z, y, u, group, bw, kernel, alpha, eps_iter, eps_gradient, max_iters, max_retries, ml_type, verbose)
}

